### PR TITLE
Access denied paths

### PR DESCRIPTION
**Pull request by mda100**
https://user-images.githubusercontent.com/17518757/128822228-ade562b5-c55c-48cd-8e3e-0ce5134a790c.mov

### CODE REVIEW

**Comment by royalsaltmerchant** [comment]
Looks great! Nice job.

**Comment by royalsaltmerchant** [comment]
@mda100 i think the only thing I would prefer changed here is: make the authorization function separate from componentDidMount and then call it in componentDidMount. This is in case there are other functions we need to call there as well.

**Comment by mda100** [comment]
hey julian! authorization is now a separate function in the root class - lmk if the try-catch on line #63 (in componentdidmount) is redundant because there is already error handling in the function being called there

**Comment by mda100** [comment]
also when someone logs in the screen briefly says "Access Denied" before showing the account page because 
the path to /account is being rendered before the authorization / componentdidmount function is called - you can see it in the video above, unsure if this is an issue for you.

**Comment by royalsaltmerchant** [comment]
@mda100 Yes so the best solution here is to have a loading state that renders a loading wheel until the authorization state changes. There should be examples on this most other components. And also that try-catch isn't necessary.

**Comment by mda100** [comment]
alright! that batch of commits corrects loading state for account and login routes. 

the state of "authenticate" and " loadingAuth" is in a few components, but lifting and abstracting it to the App component didn't work as well, the separate authenticating in Login, Account, and App seems to work fine.

**Comment by mda100** [comment]
ok! the "authenticate" function is abstracted to root component only and is called whenever root component refreshes.
"loading" is turned to true on successful login submit and successful logout to render loading screens before the page (root component) refreshes and authenticate is called 

on other paths/routes when logged in or logged out these functions don't seem to be needed, only when going from transferring between logged in and logged out states

**Comment by mda100** [comment]
https://user-images.githubusercontent.com/17518757/129977182-983444e3-7081-401a-9a8b-38073bf8adae.mov

**Pull request merged**
